-- 使用專案資料庫
CREATE
DATABASE IF NOT EXISTS teamtest;
USE
teamtest;

-- 移除既有 NEWS_IMAGE 資料表（若存在）
DROP TABLE IF EXISTS NEWS_IMAGE;

-- 建立 NEWS_IMAGE 資料表
CREATE TABLE NEWS_IMAGE
(
    IMG_NO   INT AUTO_INCREMENT NOT NULL,
    IMG_DATA longblob,
    NEWS_NO  INT          NOT NULL,
    IMG_TYPE VARCHAR(100) NOT NULL,
    CONSTRAINT NEWS_IMAGE_PK PRIMARY KEY (IMG_NO),
    CONSTRAINT NEWS_IMAGE_FK_NEWS FOREIGN KEY (NEWS_NO) REFERENCES NEWS (NEWS_NO)
) AUTO_INCREMENT = 1;